[project]
name = "nz-legislation-api"
version = "0.1.0"
description = "Python client for the NZ Legislation API"
requires-python = ">=3.10"
dependencies = [
    "httpx",
    "python-dotenv",
    "typer",
    "tqdm"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["nz_legislation"]
